[server]
enableStaticServing = true 

[theme]
primaryColor="#86C7ED"
backgroundColor="#2d2d2d"
secondaryBackgroundColor="#434343"
textColor="#f2f2f2"
font="sans serif"

[browser]
gatherUsageStats = false